creator('chevrolet').
creator('buick').
creator('plymouth').
creator('amc').
creator('ford').
creator('pontiac').
creator('dodge').
creator('toyota').
creator('datsun').
creator('peugeot').
creator('audi').
creator('saab').
creator('bmw').
creator('opel').
creator('fiat').
creator('volkswagen').
creator('mercury').
creator('oldsmobile').
creator('chrysler').
creator('mazda').
creator('volvo').
creator('renault').
creator('honda').
creator('mercedes').
creator('subaru').
creator('nissan').
creator('porsche').
creator('ferrari').
creator('mitsubishi').
creator('jeep').
creator('jaguar').
creator('lamborghini').

